name: my-rdkit-env
channels:
  - anaconda
  - conda-forge
  - defaults
  - rdkit
dependencies:
  - numpy=1.18
  - pandas=1.1.3
  - pip=20.0
  - python>=3.7
  - rdkit=2020.03
  - tqdm=4.48.0
  - pickle5
  - pip:
    - pyjanitor==0.20.10
